"""initial schema

Revision ID: a1714bc7d87e
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'a1714bc7d87e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('viewport_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('canonical_external_id', sa.String(), nullable=True),
    sa.Column('canonical_url', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=False
    )
    op.create_index(op.f('ix_source_entities_canonical_external_id'), 'source_entities', ['canonical_external_id'], unique=False)
    op.create_table('canvas_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canvas_id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=True),
    sa.Column('parent_object_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('visual_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_object_id'], ['canvas_objects.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['source_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canvas_objects_canvas_id'), 'canvas_objects', ['canvas_id'], unique=False)
    op.create_table('openalex_works_cache',
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('openalex_id', sa.String(), nullable=False),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('abstract_text', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.String(), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_topic', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('referenced_work_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('related_work_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cited_by_count', sa.Integer(), nullable=False),
    sa.Column('open_access', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['source_entities.id'], ),
    sa.PrimaryKeyConstraint('source_entity_id')
    )
    op.create_index(op.f('ix_openalex_works_cache_openalex_id'), 'openalex_works_cache', ['openalex_id'], unique=True)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canvas_id', sa.UUID(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id'], ['canvas_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_canvas_id'), 'chunks', ['canvas_id'], unique=False)
    op.create_table('object_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canvas_id', sa.UUID(), nullable=False),
    sa.Column('source_object_id', sa.UUID(), nullable=False),
    sa.Column('target_object_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_object_id'], ['canvas_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_object_id'], ['canvas_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_edges_canvas_id'), 'object_edges', ['canvas_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_object_edges_canvas_id'), table_name='object_edges')
    op.drop_table('object_edges')
    op.drop_index(op.f('ix_chunks_canvas_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_openalex_works_cache_openalex_id'), table_name='openalex_works_cache')
    op.drop_table('openalex_works_cache')
    op.drop_index(op.f('ix_canvas_objects_canvas_id'), table_name='canvas_objects')
    op.drop_table('canvas_objects')
    op.drop_index(op.f('ix_source_entities_canonical_external_id'), table_name='source_entities')
    op.drop_table('source_entities')
    op.drop_table('canvases')
    # ### end Alembic commands ###
