"""suppressions and chunk embeddings

Revision ID: e450446382e9
Revises: a1714bc7d87e
"""
from alembic import op
import sqlalchemy as sa


revision = 'e450446382e9'
down_revision = 'a1714bc7d87e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # pgvector for canvas-local RAG (PRD §15). Dimension matches
    # text-embedding-3-small; the extension is a no-op if already enabled.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("ALTER TABLE chunks ADD COLUMN IF NOT EXISTS embedding vector(1536)")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppressions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canvas_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('openalex_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppressions_canvas_id'), 'suppressions', ['canvas_id'], unique=False)
    op.create_index(op.f('ix_suppressions_openalex_id'), 'suppressions', ['openalex_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("ALTER TABLE chunks DROP COLUMN IF EXISTS embedding")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppressions_openalex_id'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_canvas_id'), table_name='suppressions')
    op.drop_table('suppressions')
    # ### end Alembic commands ###
